spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flower_db
    username: said
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
